name: unit-tests
on: [ push, pull_request ]
jobs:
    norme_test:
        runs-on: ubuntu-latest
        name: unit test
        steps:
          - uses: actions/checkout@v2
          - name: install valgrind
            run:  sudo apt install -y valgrind
          - name: make tests
            run:  make tests
